
server {
    listen 8080;
    listen [::]:8080;

    server_name 165.101.46.73;

    root /var/www/devops-hackathon-de005-dangtongocdung/src;
    index index.html;

    access_log /var/log/nginx/dangtongocdung-k24cntt3.access.log;
    error_log /var/log/nginx/dangtongocdung-k24cntt3.error.log;

    location / {
        allow all;
        try_files $uri $uri/ =404;
    }
}
